### ISSUE TITLE
Source won't compile for DotNet 4.0

### ISSUE THREAD

**Issue by DanielCaldwell** [Quobject/EngineIoClientDotNet#12]
I tried to compile the source, but it's missing references to the Socket.ClientEngine. I added these in and then it could compile. Also, I had to mark the assembly references' specific version property to false.

**Comment by mattqs** [comment]
I can compile the source using Visual Studio:

Open EngineIoClientDotNet\Src\EngineIoClientDotNet.net40\EngineIoClientDotNet.net40.sln in Visual Studio 2015 Community. Build:
```
========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========
```

**Comment by DanielCaldwell** [comment]
For anyone else who runs into this, the issue is that I was compiling my whole stack from source and when you do this, the SuperSocket ClientEngine is used as an external assembly, like normal. You can see it in the build output folders:

![image](https://cloud.githubusercontent.com/assets/2634673/9207718/24654a04-4024-11e5-9e36-449b05b28ead.png)

However, when you use the released assemblies downloaded from WebSocket4Net, you only see the WebSocket4Net assembly:

![image](https://cloud.githubusercontent.com/assets/2634673/9207754/5c97e526-4024-11e5-9ca4-d93fc2596c0b.png)


If you decompile the assembly, you can see that the SuperSocket ClientEngine is embedded in the assembly as seen here:

![image](https://cloud.githubusercontent.com/assets/2634673/9207622/9bb32bcc-4023-11e5-88f7-e7cfbf292648.png)

So the issue comes when you compile the stack from scratch, rather than use the versions included in the project.

Thanks @mattqs for looking into this for me.
