### ISSUE TITLE
'System.Collections.Generic.KeyNotFoundException' in EngineIoClientDotNet.dll when using Socket

### ISSUE THREAD

**Issue by tamasmonus-cas** [Quobject/EngineIoClientDotNet#24]
I use SocketIOClientDotNEt in WPF .net 4.5 and I get this exception when using websocket.

All I do is Emit an event, and give it a new AckImpl callback, but sometimes I got this error.

**Comment by AmerSelimovic** [comment]
I have the same problem. Any info?

**Comment by leszekm1** [comment]
This has been fixed in the beta version. (the fix was a switch to a concurrent queue).  Download the beta version from NuGet and you should be all set.

**Comment by AmerSelimovic** [comment]
Thank you very much. No problems now.
