### ISSUE TITLE
SocketIoClientDotNet support for Socket 2.0

### ISSUE THREAD

**Issue by srinisubramanian** [Quobject/EngineIoClientDotNet#33]
Given that Socket 2.0 is a breaking release, does the SocketIoClientDotNet client already support Socket server 2.0?  If not, any ETA that can be shared will be helpful.

Note: Adding to EngineIoClientDotNet as issues does not seem to be enabled for SocketIoClientDotNet

Thanks

**Comment by mattqs** [comment]
I don't have any plans to support socket.IO 2.0. As a school teacher I just don't have the time. I think you should ask Microsoft.

**Comment by srinisubramanian** [comment]
Matthias, thanks for the update.  The changes according to Socket.io are just 2.  https://github.com/socketio/socket.io/releases/tag/2.0.0  .. the issue is that once the server is updated the Socket.io .net client would not be able to connect any longer.

I will evaluate the quantum of change and check if we can submit a PR.

**Comment by mattqs** [comment]
Pull requests are welcome.

**Comment by srinisubramanian** [comment]
Will check .. looks like change also needed to Engine.io parser and socketId change to socket.io client

**Comment by mattqs** [comment]
Inadvertently I tested the latest release of https://github.com/Quobject/EngineIoClientDotNet/releases/tag/v1.0.0.1-beta1 with "engine.io": "^3.1.0" which is used by socket.IO 2.0. 
https://github.com/Quobject/EngineIoClientDotNet/blob/master/TestServer/package.json

All the tests where passing.

**Comment by srinisubramanian** [comment]
Thats interesting, never tested since I thought won't work.  Will check and update.

**Comment by srinisubramanian** [comment]
Tested and the client seems to work.  Not sure if anything needs to be done.
