### ISSUE TITLE
Response cookies are not maintained for future requests and websocket

### ISSUE THREAD

**Issue by adknie01** [Quobject/EngineIoClientDotNet#35]
Trying to use sticky sessions with AWS ALB. Need the cookie to carryover so the routing is correct. Response from polling gets a Set-Cookie: *** and future calls do not contain the cookie nor does websocket.

**Comment by endeffects** [comment]
Any upcoming fixes for thi sissue planed?

**Comment by mattqs** [comment]
There are no fixes planned. 

Sorry, but I can't provide any support for this open source project at the moment. It has
to take a back seat to my real job that provide food and a roof to live under.
