### ISSUE TITLE
Cannot upgrade to 1.0.6 into a project that targets iOS 10

### ISSUE THREAD

**Issue by peppe130** [Quobject/EngineIoClientDotNet#58]
Hi,

currently I've installed the 1.0.5 version of EngineIoClientDotNet. Today, I've saw the update of this package but I cannot install it. This is the error that appears in the console:

**Could not install package 'EngineIoClientDotNet 1.0.6'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

Any solution? Thanks.

**Comment by peppe130** [comment]
Same happens on Android:

**Could not install package 'EngineIoClientDotNet 1.0.6'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

**Comment by mattqs** [comment]
Framework Versions
.NETFramework v3.5, .NETFramework v4.0, .NETFramework v4.5
