### ISSUE TITLE
Add support for .NET Standard 2.0

### ISSUE THREAD

**Issue by KevinKibler** [Quobject/EngineIoClientDotNet#61]
There's currently a project that looks like an attempt to support .NET Standard (EngineIoClientDotNet.netstandard). It looks like it started trying to target standard 1.3, then switched to standard 2.0, but some parts are broken (e.g. passing additional headers doesn't work).

.NET Standard 2.0 added support for all the code that's currently used in the .NET 4.5 framework project. Create a new project that includes all the same source code files and targets .NET Standard 2.0 instead.

**Comment by KevinKibler** [comment]
The old netstandard project uses the WebRequest class (\Src\EngineIoClientDotNet.netstandard\Client\Transports\WebSocket_netstandard.cs:65), which isn't included .NET Standard until 2.0. If this was removed or implemented a different way, the library could probably support .NET Standard 1.3.

**Comment by KevinKibler** [comment]
Adding support for .NET Standard 1.3 might or might not be useful in practice because SocketIoClientDotNet might depend on a higher version of the standard.

**Comment by mattqs** [comment]
https://github.com/Quobject/SocketIoClientDotNet/issues/146

**Comment by KevinKibler** [comment]
Any idea when this might get released?

**Comment by mattqs** [comment]
Support for NetStandard will be added again when WebSocket4Net works with .NETStandard 2.0. See #145
https://www.microsoft.com/net/download/visual-studio-sdks
