### ISSUE TITLE
No lock

### ISSUE THREAD

**Issue by ashegoulding** [Quobject/EngineIoClientDotNet#65]
From: https://gamedev.amazon.com/forums/articles/70528/gamelift-service-processauxproxy-terminates-health.html

> Yes, there's something wrong with timeout... But there's a bigger problem: false timeout was random because there is a race condition going on in the code. Clearly, the developer didn't know what they were doing. Threads are used to implement event system and lock is no where to be found.
> 
> Two classes are responsible for calling `OnHeartbeat()` where `PingTimeoutTimer` is reset. The timer is reset when a pong packet is received from the server. The timer is also reset every time a packet is received. "Pinging" or "heartbeat" is by definition checking on the connection on a regular interval. So in this case, the timeout event is delayed if any packet is received causing the two timers(another one being `PingIntervalTimer`) out of sync. But even if they are not in sync, the ping timer works fine as long as the server responds to ping packets. The problem is `OnHeartbeat()` could be run at the same time by multiple threads. It is possible that the previous timeout timer is left unstopped. That explains the random behaviour. `EasyTimer` is implemented using Task in net 4.5 version and BackgroundWorker thread in net 3.5.

See [this commit](https://github.com/fixstu/EngineIoClientDotNet/commit/4761924fa73391497e719b8afb6007ae12aaf4eb). I kinda get your intention on why `OnHeartbeat()` is called from two places, but I removed one of them to avoid the race condition.

**PLACE LOCKS**

**Comment by ashegoulding** [comment]
Well played, doctor. Just know that some people can't sleep at night because of code you wrote few years ago.

**Comment by mattqs** [comment]
https://github.com/Quobject/SocketIoClientDotNet#nb
