### ISSUE TITLE
On method  expose  only one parameter, action<object> although it is possible by the engine.io-client api

### ISSUE THREAD

**Issue by maty21** [Quobject/EngineIoClientDotNet#8]
I'm trying to get more the one parameter with On method  but it impossible because the api exposes only action<> or action<object>

is it something that you plan to support in the near future or i have to implement it by myself thanks

**Comment by mattqs** [comment]
If you look at the source code [ComponentEmitter.cs lines 66-88](https://github.com/Quobject/EngineIoClientDotNet/blob/master/Src/EngineIoClientDotNet.mono/ComponentEmitter/Emitter.cs):

        /// <summary>
        ///  Listens on the event.
        /// </summary>
        /// <param name="eventString">event name</param>
        /// <param name="fn"></param>
        /// <returns>a reference to this object</returns>
        public Emitter On(string eventString, Action fn)
        {
            var listener = new ListenerImpl(fn);
            return this.On(eventString, listener);
        }

        /// <summary>
        ///  Listens on the event.
        /// </summary>
        /// <param name="eventString">event name</param>
        /// <param name="fn"></param>
        /// <returns>a reference to this object</returns>
        public Emitter On(string eventString, Action<object> fn)
        {
            var listener = new ListenerImpl(fn);
            return this.On(eventString, listener);
        }

you can see that the methods On(..., Action ...) are only convenience methods. They all pass on to the main 'On' method [ComponentEmitter.cs lines 46-64](https://github.com/Quobject/EngineIoClientDotNet/blob/master/Src/EngineIoClientDotNet.mono/ComponentEmitter/Emitter.cs):

        /// <summary>
        ///  Listens on the event.
        /// </summary>
        /// <param name="eventString">event name</param>
        /// <param name="fn"></param>
        /// <returns>a reference to this object</returns>
        public Emitter On(string eventString, IListener fn)
        {
            if (!this.callbacks.ContainsKey(eventString))
            {
                //this.callbacks[eventString] = ImmutableList<IListener>.Empty;
                this.callbacks = this.callbacks.Add(eventString, ImmutableList<IListener>.Empty);
            }
            ImmutableList<IListener> callbacksLocal = this.callbacks[eventString];
            callbacksLocal = callbacksLocal.Add(fn);
            //this.callbacks[eventString] = callbacksLocal;
            this.callbacks = this.callbacks.Remove(eventString).Add(eventString, callbacksLocal);
            return this;
        }

which takes as the second parameter a `IListener` object [ComponentEmitter.cs lines 210-214](https://github.com/Quobject/EngineIoClientDotNet/blob/master/Src/EngineIoClientDotNet.mono/ComponentEmitter/Emitter.cs):
    
    public interface IListener: System.IComparable<IListener>
    {
        int GetId();
        void Call(params object[] args);
    }

You can write your own IListener Implementation that takes as many parameter as you want. The IListener implementation that I have provided [ComponentEmitter.cs lines 216-261](https://github.com/Quobject/EngineIoClientDotNet/blob/master/Src/EngineIoClientDotNet.mono/ComponentEmitter/Emitter.cs):

    public class ListenerImpl : IListener
    {
        private static int id_counter = 0;
        private int Id;
        private readonly Action fn1; 
        private readonly Action<object> fn;

        public ListenerImpl(Action<object> fn)
        {

            this.fn = fn;
            this.Id = id_counter++;
        }

        public ListenerImpl(Action fn)
        {

            this.fn1 = fn;
            this.Id = id_counter++;
        }

        public void Call(params object[] args)
        {
            if (fn != null)
            {
                var arg = args.Length > 0 ? args[0] : null;
                fn(arg);
            }
            else
            {
                fn1();
            }
        }

        

        public int CompareTo(IListener other)
        {
            return this.GetId().CompareTo(other.GetId());
        }

        public int GetId()
        {
            return Id;
        }
    }

might help you with your own implementation of IListener.

By using IListener you should be able to do everything you can do with the javascript client.

See also [Acknowledge event emitted by server #12](https://github.com/Quobject/SocketIoClientDotNet/issues/12).
