### ISSUE TITLE
Nested EVENT_MESSAGE event handler registration

### ISSUE THREAD

**Issue by DominikPalo** [Quobject/EngineIoClientDotNet#9]
Why is in example registration of EVENT_MESSAGE event nested (doubled)?

    var socket = new Socket("ws://localhost");
    socket.On(Socket.EVENT_OPEN, () =>
    {
        socket.On(Socket.EVENT_MESSAGE, (data) =>
        {
            socket.On(Socket.EVENT_MESSAGE, (data) => Console.WriteLine((string)data));
        });
    });
    socket.Open();  

I'm using in my app only single `socket.On(Socket.EVENT_MESSAGE, (data) => {...});` after opening the socket and all works fine. Is there any reason for nested registration, or it is only mistake in example code?

**Comment by mattqs** [comment]
This is the Engine.IO Client Library for C#, which is ported from the [JavaScript client](https://github.com/Automattic/engine.io-client).

I just ported everything from the javascript client. They are doing it this way, that's why I did it as well.

**Comment by DominikPalo** [comment]
Ok, but I think, there is problem in commit https://github.com/Quobject/EngineIoClientDotNet/commit/e04e56d24839f29c93ef0f3f093bfb36ca526c03#diff-04c6e90faac2675aa89e2176d2eec7d8 Line 37 

    socket.On(Socket.EVENT_MESSAGE, (data) => Console.WriteLine((string)data));

of README.MD should replace entire block

 	socket.On(Socket.EVENT_MESSAGE, (data) =>
 	{
		var dataString = (string)data;
		Console.WriteLine(dataString);
		socket.Close();
 	});

not only these lines:

		var dataString = (string)data;
		Console.WriteLine(dataString);
		socket.Close();


I checked README.MD file of JavaScript client and there is no nested registration of a MESSAGE handler in any revision...

**Comment by mattqs** [comment]
Fixed README.MD in 84e8daee7ff7c699ca4a655b71c89ff267097696.
